### ISSUE TITLE
_cropperjs2.default is not a constructor

### ISSUE THREAD

**Issue by ednar28** [Agontuk/vue-cropperjs#104]
I'm using  vite 2.1.2 and vue 3.0.5

```
<template>
     <vue-cropper
        ref="cropper"
        drag-mode="move"
        :center="true"
        :crop-box-movable="false"
        :crop-box-resizable="false"
        :min-container-height="80"
        :src="imageUrl"
        :aspect-ratio="16 / 9"
        :auto-crop-area="100"
        :modal="false"
        :guides="false"
        alt="Source Image"
        @ready="ready"/>
</template>

<script>
import VueCropper from 'vue-cropperjs'
import 'cropperjs/dist/cropper.css'
export default {
  components: {
    VueCropper,
  },
}
</script>
```
![image](https://user-images.githubusercontent.com/49565820/120176565-a0afe480-c231-11eb-87bb-a9689204fb5a.png)

**Comment by Agontuk** [comment]
Can you please check if cropperjs is installed and which version is installed ?

**Comment by ednar28** [comment]
![image](https://user-images.githubusercontent.com/49565820/120245451-7264f000-c297-11eb-8d56-7e4482cd3e4d.png)
I after checked the folder. I like playing with magic.

ty for your response and sorry create a new issue
