### ISSUE TITLE
Problem using library with Quasar framework. 

### ISSUE THREAD

**Issue by coupej** [Agontuk/vue-cropperjs#11]
When trying to use the Quasar Framework http://quasar-framework.org/ and trying to include the library I get the following error: VueCropper.js?f133:8 Uncaught TypeError: Vue.extend is not a function
<img width="1280" alt="schermafbeelding 2017-03-12 om 01 18 39" src="https://cloud.githubusercontent.com/assets/912039/23835656/89f7c210-076b-11e7-856f-088e123471b3.png">

I used your library before and then "it just worked".

I attached a zip with a standard quasar project and the cropperjs lib included. Once i added the 
`import VueCropper from 'vue-cropperjs'` line in the index.vue file the error happens. 

[bugSar.zip](https://github.com/Agontuk/vue-cropperjs/files/836946/bugSar.zip)

Should you want to reproduce I think you would need 

`npm install -g quasar-cli` to install the quasar framework cli
`quasar dev` to get the project running. offcourse after all the npm dependencies are installed.

**Comment by coupej** [comment]
I got it working by including the  vue: 'vue/dist/vue.js' alias in the resolve section of my webpack config as described at https://github.com/vuejs-templates/webpack/issues/215. This however means that it will use the "full" vue install instead of the runtime only build. 

I would prefer that I could get a compiled version of the plug-in in my build instead.

**Comment by Agontuk** [comment]
Thanks for the  feedback, I'll look into it.

**Comment by Agontuk** [comment]
I've published a new version with the fix, can you check it and let me know if it works for you ? I'll close the issue then.

**Comment by coupej** [comment]
It works for me! Thanks for your quick reply.
