### ISSUE TITLE
Vue-Cropperjs issue with 5.0.0 version 

### ISSUE THREAD

**Issue by manishrws** [Agontuk/vue-cropperjs#118]
I am getting error with latest version of vue-cropperjs (5.0.0). The code is working fine with older version 4.2.0.

![image](https://user-images.githubusercontent.com/105245502/167492541-dc335670-b442-4224-8f8c-18c615270aca.png)

The error is -  Error in mounted hook: "Error: The first argument is required and must be an <img> or <canvas> element."

Can you please help me out for this issue.

**Comment by aibow** [comment]
5.x.x only use vue3
4.x.x only use vue2

vue3 and vue2 is not compatible

**Comment by Agontuk** [comment]
As @aibow said, 5.0.0 is only for vue 3.
