### ISSUE TITLE
Can't see autoCrop Layout on image

### ISSUE THREAD

**Issue by paker-zhang** [Agontuk/vue-cropperjs#119]
Hello, @Agontuk 
I got a problem with display autoCrop Layout.
There is my [example code](https://codesandbox.io/s/cropperjs-vue-v25s8c?file=/src/App.vue).

I tried to lookup cropperjs and vue-cropperjs document, autoCrop default is true. 

I'm not sure what wrong I have done, if you know anything about this, please let me know.

Thank you.

**Comment by Agontuk** [comment]
Your prop passing is wrong, it should be like this

```js
<VueCropper
  ref="cropper"
  :src="image"
  :viewMode="1"
  :guides="true"
  :autoCrop="true"
  :autoCropArea="0.8"
/>
```

And use images that don't have cross origin issue

**Comment by paker-zhang** [comment]
Thanks for your help.
