### ISSUE TITLE
How to set fixed width and height?

### ISSUE THREAD

**Issue by elmatadorrr** [Agontuk/vue-cropperjs#15]
I have my component like this:

`<vue-cropper
       ref='cropper'
        :guides="cropOptions.guides"
        :view-mode="cropOptions.viewMode"
        :drag-mode="cropOptions.dragMode"
        :auto-crop-area="cropOptions.autoCropArea"
        :min-container-width="cropOptions.minContainerWidth"
        :min-container-height="cropOptions.minContainerHeight"
        :min-crop-box-width="cropOptions.minCropBoxWidth"
        :min-crop-box-height="cropOptions.minCropBoxHeight"
        :background="cropOptions.background"
        :movable="cropOptions.movable"
        :crop-box-movable="cropOptions.cropBoxMovable"
        :crop-box-resizable="cropOptions.cropBoxResizable"
        :src="imgSrc"
        alt="Source Image"
        :imgStyle="cropOptions.imgStyle"/>
</vue-cropper>`

I have tried something like this:

`this.$refs.cropper.setCropBoxData({width: '20', height: '50', top: '0', left: '0'})`

but it's not working...

Any help?

**Comment by Gagydzer** [comment]
@elmatadorrr hi, i faced same problem. How do you fixed it?

**Comment by andreim-13** [comment]
Can anybody provide a solution to this? Still the same issue - setCropBoxData or setData methods do nothing. No error messages either.

**Comment by cristinafsanz** [comment]
I was having the same problem and I then I saw that you can execute the `setCropBoxData` from the `ready` method of `vue-cropped`:

```
<vue-cropper
      ref="cropper"
      @ready="..."
      >
```
Just in case someone has this problem in the future.

**Comment by webkawsar** [comment]
I faced same problem

**Comment by webkawsar** [comment]
I faced same problem. How it is possible to solve?

**Comment by webkawsar** [comment]
It is solved in way 
<VueCropper 
                    :min-container-width="250"
                    :min-container-height="180" 
                    v-show="selectedFile" 
                    ref="cropper" 
                    :src="selectedFile" 
                    alt="Source Image"
                    :img-style="{ width: '400px', height: '300px' }"
                 ></VueCropper>

**Comment by webkawsar** [comment]
solved in way <VueCropper 
                    :min-container-width="250"
                    :min-container-height="180" 
                    v-show="selectedFile" 
                    ref="cropper" 
                    :src="selectedFile" 
                    alt="Source Image"
                    :img-style="{ width: '400px', height: '300px' }"
                  ></VueCropper>

**Comment by webkawsar** [comment]
solved in way :img-style="{ width: '400px', height: '300px' }"
