### ISSUE TITLE
warning prop "style"

### ISSUE THREAD

**Issue by mamor** [Agontuk/vue-cropperjs#17]
Hello :)

since vuejs v2.3 https://github.com/vuejs/vue/releases/tag/v2.3.0, the following warning occored.

```
[Vue warn]: "style" is a reserved attribute and cannot be used as component prop.

found in

---> <VueCropper>
```

Is there a way to fix it?

**Comment by Agontuk** [comment]
Thanks for the report, I'll check it out. Probably need to do a breaking change since `style` is now treated as a reserved keyword
