### ISSUE TITLE
no babel for vue 1+ @1.0.3 

### ISSUE THREAD

**Issue by ChZoe** [Agontuk/vue-cropperjs#18]
template: `
        <div :style="style">
            <img
                v-el:img
                :src="src"
                :alt="[ alt === undefined ? 'image': alt ]"
                style="max-width: 100%;"
                :style="imgStyle"
            />
        </div>
    `,

Es6 template strings，as above,  cant be compiled correctly in @1.0.3

**Comment by Agontuk** [comment]
babel es2015 preset is needed for compiling es6 syntax. It'll work if you include the preset.
