### ISSUE TITLE
Props call Style is a reserved attribute and cannot be used as a prop component

### ISSUE THREAD

**Issue by HugoOliveiraThor** [Agontuk/vue-cropperjs#19]
This is the warn that Vue Version 2.2.6 when we call the component the warning message appears . 

Message 
console.js?93a0:26 [Vue warn]: "style" is a reserved attribute and cannot be used as component prop.

**Comment by Agontuk** [comment]
I fixed it but did not publish it yet. I'll publish it tonight.

**Comment by erbing** [comment]
Can a bit faster, I am more worry

**Comment by Agontuk** [comment]
published new version with the fix, use `containerStyle` prop to style the container from now on.
