### ISSUE TITLE
:zoom Event not attaching correctly

### ISSUE THREAD

**Issue by MikeyWallis** [Agontuk/vue-cropperjs#24]
I have a cropper in a component like so:

`<vue-cropper  :ref="'cropper'" :src="imgSrc" :zoom="testMethod" :view-mode="3" :guides="false" :background="false" :drag-mode="'move'" :auto-crop-area="1" :crop-box-movable="false" :crop-box-resizable="false"></vue-cropper>`

And then a test method I'm using which is as follows:

```
testMethod() {
            console.log('Working');
            var currentWidth = this.$refs.cropper.getCanvasData().width;
            console.log(currentWidth);
        }  
```

If I use any of the cropmove, start or end methods the function fires and I get the logged output, however when I use zoom I get nothing. 

I'm using Chrome version 59.0.3071.115 (Official Build) (64-bit) on a Macbook Pro running Sierra. I've tested zooming with both the mouse wheel and the trackpad

**Comment by Agontuk** [comment]
zoom event is currently disabled I think. I faced an issue while updating this library for Vue 2.0, so disabled it back then. I'll take a look to see if I can fix it.

**Comment by MikeyWallis** [comment]
Great! Thanks

**Comment by Agontuk** [comment]
I pushed a fix in the master branch. Can you check if it works for you, I'll then update the npm version.

**Comment by Agontuk** [comment]
zoom event should work now, so closing this.
