### ISSUE TITLE
this is using a very old version of cropperjs ?

### ISSUE THREAD

**Issue by vesper8** [Agontuk/vue-cropperjs#27]
Just checked the dependency in package.json

```
    "cropperjs": "~0.8.x"
```

And checked npm info | grep cropper and indeed only the 0.8.1 is installed

That version came out more than 1 year ago. They are up to a stable 1.1.3 now

Any chance you can update this package to work with the 1.x branch?

Thanks!

**Comment by Agontuk** [comment]
I didn't update to the latest cropperjs version because it probably has some breaking changes. I'll give it another try as soon as possible.

**Comment by Agontuk** [comment]
New version is released with the latest cropperjs version. Feel free to try it out and see if it works.
