### ISSUE TITLE
vue2.0 build error

### ISSUE THREAD

**Issue by BusyHe** [Agontuk/vue-cropperjs#3]
ERROR in ../static/js/vendor.d4090d62fe572c3ca742.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/vue-cropperjs/VueCropper.js:140,0]

**Comment by Agontuk** [comment]
This is probably a build tool issue on your end. Line 140 is the declaration of a function, which is totally fine.
Maybe your transpiler wants function to be declared like this
`
reset: function () {}
`
instead of
`
reset () {}
`

**Comment by BusyHe** [comment]
thank you, i try

**Comment by BusyHe** [comment]
`import VueCropper from 'vue-cropperjs'`
i use webpack+vue,when i whrite this line ,errror

**Comment by Agontuk** [comment]
I'm pretty sure it's a webpack configuration issue, You can search for it or I can take a look if you can give me a sample project.

**Comment by BusyHe** [comment]
thank,You're right
it's a webpack configuration issue
`ERROR in ../static/js/vendor.e64b61ec57c2a4f1894b.js from UglifyJs
`

**Comment by BusyHe** [comment]
```
{
                test: /\.js$/,
                loader: 'babel',
                include: [
                    path.resolve(__dirname, '../config'),
                    path.resolve(__dirname, '../build'),
                    path.resolve(__dirname, '../src'),
                    path.resolve(__dirname, '../node_modules/vue-cropperjs'),
                ]
            },
```
 I solved

**Comment by Agontuk** [comment]
nice, I'll close the issue.
