### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by amdad** [Agontuk/vue-cropperjs#30]
Hello, thank you for component.

I'm new in vue world. But when I comparing Vanilla Cropper, then your version is much more laggy (selecting, zooming, moving). It is Vue wrapping problem? Vue always slow down vanilla this way or this is something with your code?

Thanks!

**Comment by Agontuk** [comment]
How are you testing this? If you're using the example I provided, yes the example is a bit laggy. It's because it's generating base64 image every time user drags the image.

**Comment by amdad** [comment]
Yes, on demo. Oh, that's the reason. Thanks for reply.

**Comment by VeeeneX** [comment]
@amdad Why did you closed this? We are experiencing same problem with more than 100 croppers on the page which makes it crash after a while.

**Comment by amdad** [comment]
100 croppers on one page and you say it's leggy? No shit Sherlock XD

**Comment by VeeeneX** [comment]
@amdad Thank you Watson but the problem was somewhere else, this cropper is capable of making hundreds of croppers active in same time so, for anyone else experiencing this issue it's not the problem in the cropper :)

**Comment by amdad** [comment]
Sherlock, you have brain indeed!  😁
