### ISSUE TITLE
this.$refs.cropper.zoom is not defined

### ISSUE THREAD

**Issue by qilvnuanqingyou** [Agontuk/vue-cropperjs#35]
console.log(this.$refs.cropper);
I see the 'zoom' is undefined, I want to use button to trigger zoom, can you add this methods

**Comment by Agontuk** [comment]
`zoom` method is replaced with `relativeZoom`, since there's already a event with the same name. Check if it works for you.

**Comment by qilvnuanqingyou** [comment]
@Agontuk it works,thanks a lot

**Comment by gmbeke** [comment]
I have an issue on this and Im using vue3 : this.$refs.cropper.getCropper() is not a function
