### ISSUE TITLE
SyntaxError Unexpected token .

### ISSUE THREAD

**Issue by sotisoti** [Agontuk/vue-cropperjs#39]
Not sure if it supports Nuxtjs, but I am getting SyntaxError Unexpected token . when I try to load a page,
I have built a very simple repo for this error.

https://github.com/sotisoti/cssloader_test

**Comment by sotisoti** [comment]
I end up using another library.

**Comment by kapvik** [comment]
> I end up using another library.

Have same issue, what library you use now?

**Comment by sotisoti** [comment]
> > I end up using another library.
> 
> Have same issue, what library you use now?

I use [https://github.com/zhanziyang/vue-croppa](https://github.com/zhanziyang/vue-croppa), it's fairly easy to configure. Check it out.

**Comment by kapvik** [comment]
> > > I end up using another library.
> > 
> > 
> > Have same issue, what library you use now?
> 
> I use https://github.com/zhanziyang/vue-croppa, it's fairly easy to configure. Check it out.

Thanks

**Comment by koibi2** [comment]
我刚刚解决了！
在 `node_modules/vue-cropperjs/dist/VueCropper.js` 注释这一行：
![image](https://user-images.githubusercontent.com/34370367/56862410-333f8300-69dd-11e9-9aaa-796e1fc73cea.png)

然后在 VUE 页面的 style 引入即可。
```
<style lang="scss">
@import "cropper.css";
```
p.s:估计这是JS引用CSS报错导致的。肯定有更好的解决方法，如webpack配置。
有好的方法。欢迎下面留言。

**Comment by Agontuk** [comment]
@ataylor32 , seems like your setup is not recognizing the css syntax. Can you check if you can enable css loader so that it can parse css ?

**Comment by ataylor32** [comment]
@Agontuk I'm using this:

```js
{
  test: /\.css$/,
  loader: ['vue-style-loader', 'css-loader'],
},
```

This is only an issue with server-side rendering. My project is based on an official Vue demo app,
[vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0).

**Comment by Agontuk** [comment]
Can you give me a example repo so that I can reproduce the issue on my end ? I have yet to try out the server side rendering in vue so don't know the exact issue.

**Comment by ataylor32** [comment]
I forked that official Vue demo app,
[vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0), created a branch called `vue-cropperjs-issue-39`, and made [one commit](https://github.com/ataylor32/vue-hackernews-2.0/commit/0b5a5955b3a233661e00560ac9c194e9213afdb1).

Here are the steps you can go through to reproduce the problem on your own computer:

1. Clone `https://github.com/ataylor32/vue-hackernews-2.0.git`

1. Check out the `vue-cropperjs-issue-39` branch

1. Run `npm ci`

1. Start the site in development mode by running `npm run dev`

1. Go to http://localhost:8080/top in your browser and click on one of the comments links. You will be navigated to a comments page and if you look below the header, you'll see a file input. Browse for a GIF, JPG, or PNG and you'll see that vue-cropperjs is working fine. Now refresh the page (i.e. try to get server-side rendering to render the page) and it will break. Stop the site with Ctrl+C.

1. Start the site in production mode by running `npm run build && npm start` and then repeat the previous step and you'll see that it behaves the same in production mode

Thank you!

**Comment by Agontuk** [comment]
Thanks for the detailed steps, I'm checking out the vue ssr guide to get familiar with it. Then I'll check on the issue.

**Comment by Agontuk** [comment]
@ataylor32 , sorry for the late response. New version 4.0.0 is published and should work on SSR now. Note that default css import is removed now so you have to import it in your file where you're using it. Readme has been updated.

**Comment by ataylor32** [comment]
No problem. Thanks for fixing it! It works for me now.
