### ISSUE TITLE
Vue CropperJS throws error in IE11 when uploading .gif or .png

### ISSUE THREAD

**Issue by 06b** [Agontuk/vue-cropperjs#43]
When uploading a .png or .gif in IE11 a console error is thrown and the cropper will not appear.

**Vue CropperJS error example in IE11**
![VueCropperJs-Bug](https://user-images.githubusercontent.com/1302542/55351612-d065d500-548c-11e9-95ee-46a769fbc83a.gif)

This appears to happen after cropperjs released 1.5.0 as 1.4.3 still works with vue-cropperjs. 

**Vue CropperJS 1.4.3 example in IE11**
![VueCropperJs143-Bug](https://user-images.githubusercontent.com/1302542/55351395-3a31af00-548c-11e9-8e25-d68862ddad7e.gif)

The following repo example can be used to test in IE11 where it still works - https://github.com/06b/vue-cropperjs/tree/cropperjs-1.4.3

I've attempted to recreate the issue in cropperjs only and was unable to recreate the issue.

**Comment by Agontuk** [comment]
Thanks, I'll check it out. If you can find a fix, please open a PR.

**Comment by 06b** [comment]
It appears that this issue has been fixed with the release of cropperjs 1.5.4, so I'm going to close this issue and the pull request that fixes this issue however I'll keep the one which fixes the example page to work in IE11 open.
