### ISSUE TITLE
[fix]: i don't see any Events Support

### ISSUE THREAD

**Issue by zhougonglai** [Agontuk/vue-cropperjs#51]
```javascript
h('img', {
      ref: 'img',
      attrs: {
        src: this.src,
        alt: this.alt || 'image',
        style: 'max-width: 100%'
      },
    nativeOn: {  // missing this
      ready: this.ready,
      cropstart: this.cropstart, // ...
    },
      style: this.imgStyle
    })]
```

These events are provided with props but not on Cropper Element

**Comment by elanclarkson** [comment]
+1 I need this so I can pass context with the cropend event.

**Comment by MustafaOmarIbrahim** [comment]
+2

**Comment by MustafaOmarIbrahim** [comment]
+2 they supposed to be events not as props.
it would be nice if they are like this.
```vue
<vue-cropper
  @ready="readyFired"
  @cropstart="cropstartFired"
  @cropmove="cropmoveFired"
  @cropend="cropendFired"
  @crop="cropFired"
  @zoom="zoomFired">
</vue-cropper>
```

**Comment by zacharytyhacz** [comment]
Yes +1, cropperjs shows it has events 

https://github.com/fengyuanchen/cropperjs#events

but `v-on:event` or `@event` dont work with them!

**Comment by themustafaomar** [comment]
I've sent a pull request to fix this issue, but the owner is not here 🙄!
Pull request: https://github.com/Agontuk/vue-cropperjs/pull/63
Commit: https://github.com/Agontuk/vue-cropperjs/pull/63/commits/bd0be38e77526dba119180b3d23871c7156c8d8b

**Comment by zacharytyhacz** [comment]
@themustafaomar  Awesome man! Was thinking of going in there myself to make a pull request like you have. Let's urge @Agontuk  to merge

**Comment by pintoflager** [comment]
In case this never gets committed you can use .native modifier to hook into cropperjs event:
@crop.native="crop($event)"

**Comment by Agontuk** [comment]
Event support added in v4.1.0
