### ISSUE TITLE
Update version on package.json and on npmjs.com

### ISSUE THREAD

**Issue by KocaHocTpa2** [Agontuk/vue-cropperjs#58]
Good afternoon.
Please upgrade your library so that npmjs.com can update it on our own and we get the update.

https://github.com/Agontuk/vue-cropperjs/pull/56

**Comment by Mazeland** [comment]
The package.json is changed, but you didn't update the release for this app. Could you please update this?

**Comment by Agontuk** [comment]
4.0.1 is available in npm
