### ISSUE TITLE
How to download cropped image

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [Agontuk/vue-cropperjs#61]
It is blocked, why?

**Comment by Agontuk** [comment]
Sorry didn't understand your question, can you elaborate ?

**Comment by Bexazak** [comment]
@rahulkumarsingh73690  means it
![image](https://user-images.githubusercontent.com/14177205/94277211-e81efc00-ff51-11ea-9a34-31582ababad0.png)

**Comment by rahulkumarsingh73690** [comment]
> @rahulkumarsingh73690 means it
> ![image](https://user-images.githubusercontent.com/14177205/94277211-e81efc00-ff51-11ea-9a34-31582ababad0.png)

Demo pic is dashing :)
