### ISSUE TITLE
Unable to clear the selected image

### ISSUE THREAD

**Issue by nareshbabu557** [Agontuk/vue-cropperjs#64]
Hi,

I can't get this working, once I select the image, I'm trying reset the image whenever modal is closed. Is there any way to reset the cropper to initial state without image src?

I tried to set `src` to `null`, but it is not working.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/20286571/74609103-c41e5100-510c-11ea-9fd2-2f1a4d10195d.png">

**Comment by Agontuk** [comment]
Use `this.$refs.cropper.reset()`

**Comment by consciousnessdev** [comment]
> Hi,
> 
> I can't get this working, once I select the image, I'm trying reset the image whenever modal is closed. Is there any way to reset the cropper to initial state without image src?
> 
> I tried to set `src` to `null`, but it is not working.
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/20286571/74609103-c41e5100-510c-11ea-9fd2-2f1a4d10195d.png">

How do you setup vue-cropper in modal? can you share sourcecode?
