### ISSUE TITLE
[Question] How can I crop a rounded image?

### ISSUE THREAD

**Issue by revington** [Agontuk/vue-cropperjs#78]
Cropper demo here https://fengyuanchen.github.io/cropperjs/examples/crop-a-round-image.html

**Comment by Agontuk** [comment]
You can checkout the source code here [https://github.com/fengyuanchen/cropperjs/blob/master/docs/examples/crop-a-round-image.html](https://github.com/fengyuanchen/cropperjs/blob/master/docs/examples/crop-a-round-image.html)

**Comment by revington** [comment]
Hey @Agontuk that is the same example I have submitted. My question is about how to do it with vue-cropperjs

**Comment by Agontuk** [comment]
Not sure what you're asking, vue-cropperjs is the same as cropperjs. Just use the same code used in the example
1) use getCroppedCanvas to get the cropped area
2) copy & use `getRoundedCanvas` function to get rounded image from cropped canvas
3) use `toDataURL` to get the base64 image.

**Comment by FrenchGithubUser** [comment]
Hi ! I saw the example code for cropperjs.

However, what I'd like to do would be to have a rounded preview (like in the example) and a squared crop. Is there a way to do that ?
