### ISSUE TITLE
error in build app while using typescript

### ISSUE THREAD

**Issue by ProMasoud** [Agontuk/vue-cropperjs#79]
Hi, 
Thanks for your awesome work on cropper.js wrapper

I have problem with this plugin while using TypeScript.
The problem is plugin not support typescript and I have error in build and deploy my app

![image](https://user-images.githubusercontent.com/16334025/89031081-05b35900-d347-11ea-8773-6f56ad3595ac.png)

**Comment by Agontuk** [comment]
I'll try to add typescript support, also PR is welcome.

**Comment by rcart** [comment]
Hi @ProMasoud , were you able to tackle this issue with a solution/workaround? I'm experiencing the exact same scenario as you did.

**Comment by ProMasoud** [comment]
Hi @rcart 
Yes I simply did this. It 's not a good idea but working.

```
  public cropImage(): void {
    this.cropImg = (this.$refs.cropper as any).getCroppedCanvas().toDataURL();
    this.form.avatar = this.cropImg;
    this.dialog = false;
  }
  ```

**Comment by rcart** [comment]
Cool. That did the trick @ProMasoud. Thanks a lot.
