### ISSUE TITLE
Problems with CORS

### ISSUE THREAD

**Issue by CeloHill** [Agontuk/vue-cropperjs#82]
I'm having a problem with CORS when I try to access images from my API.

"Access to image at 'http://localhost:8000/games/galerias/artworks/1/final_fantasy_xii_poster_promocional_penelo_2343.jpg?timestamp=1600045218256' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

When I use an url from inside the save origin everything works perfectly, but when I change to my API the error appears and the crop doesn't work. The image is there, but don't work.

![image](https://user-images.githubusercontent.com/4058897/93033569-25f45a00-f60d-11ea-882f-b6a129c49896.png)

I tryed to set checkCrossOrigin and checkOrientation...

```
:checkCrossOrigin="true"
:checkOrientation="false"
```
but doesnt work... the image tag I can't change on vue version...
Anyone has any idea how to solve it?

**Comment by CeloHill** [comment]
Hi, people. I set checkCrossOrigin as false and it's working!
`:checkCrossOrigin="true"`

I hope this can help anyone with this problem.

**Comment by Agontuk** [comment]
Glad it worked out, closing this.
