### ISSUE TITLE
Vue 3?

### ISSUE THREAD

**Issue by 9mm** [Agontuk/vue-cropperjs#83]
Hey I was wondering if there were plans to support Vue 3.

**Comment by masoudelahi** [comment]
> Hey I was wondering if there were plans to support Vue 3.

i'm too

**Comment by masoudelahi** [comment]
is it compatible with Vue 3.

**Comment by Agontuk** [comment]
It should work with vue 3 without any changes, please try & let me know if it's not the case.

**Comment by SmallComfort** [comment]
@Agontuk In vue3 the $listeners has been removed，I found $listeners is used in your code

**Comment by RichPC** [comment]
@Agontuk just tried it with vue3 and got the following error:

```
Uncaught TypeError: h is not a function
    at Proxy.render (VueCropper.js?95c3:19)
```

h needs to be imported with vue3

`import { h } from 'vue'`

but then as @SmallComfort pointed out the $listeners have gone too.

**Comment by Agontuk** [comment]
I'll add vue 3 support asap, seems like it'll be a breaking change though.

**Comment by MarceloLuis1997** [comment]
+1

**Comment by Agontuk** [comment]
Master branch now contains vue 3 related changes, you can try & see if it works for you. I'll release a major version soon.

**Comment by matslindh** [comment]
For anyone wondering: since `this.$refs` isn't available in the new `setup()` in Vue3, you can get a reference to `cropper` by using `ref`:

    setup(props) {
      const cropper = ref(null);
      return { cropper, }
    }

The `croppper` reference will be populated with a reference to the actual `cropperjs` instance, and you can access the instance through `cropper.value`.

**Comment by Agontuk** [comment]
v5.0.0 has been published with vue 3 support
