### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by damianlluch** [Agontuk/vue-cropperjs#90]
Hi! thanks for your job.

In your example not set value the values of this properties. You can provide an example please?

thanks!

  @ready="..."
  @cropstart="..."
  @cropmove="..."
  @cropend="..."
  @crop="..."
  @zoom="..."

**Comment by christhofer** [comment]
Attributes started with `@` is an event handler that receive a function to be called
For example if you have <button @click="myFunction">click me</button>, myFunction() will be called when the button is clicked.
They are optional, most likely you don't need most of them.

This plugin is just a vue wrapper for [cropperjs](https://github.com/fengyuanchen/cropperjs), you should read the complete docs there

**Comment by Agontuk** [comment]
As @christhofer pointed out, you can checkout the documentation in cropperjs repo.
