### ISSUE TITLE
Error in render: "TypeError: (0 , _vue.h) is not a function"

### ISSUE THREAD

**Issue by im-fahad** [Agontuk/vue-cropperjs#98]
`[Vue warn]: Error in render: "TypeError: (0 , _vue.h) is not a function"
TypeError: (0 , _vue.h) is not a function
[Vue warn]: Error in mounted hook: "Error: The first argument is required and must be an <img> or <canvas> element."
Error: The first argument is required and must be an <img> or <canvas> element.`

All errors come from the VueCropper.js v5.0.0

**Comment by Agontuk** [comment]
Are you using vue 2 or vue 3 ? For vue 2, use v4.2.0.

**Comment by im-fahad** [comment]
I am using vue 2, Thanks.
